[package]
name = "sqlx-db-tester"
version = "0.1.0"
authors = ["Tyr Chen <tyr.chen@gmail.com>"]
edition = "2021"
license = "MIT"
documentation = "https://docs.rs/"
repository = "https://github.com/tyrchen/"
homepage = "https://github.com/tyrchen/"
description = """

"""
readme = "README.md"
categories = ["development-tools"]
keywords = []

[dependencies]
sqlx = { version = "0.6.2", features = ["postgres", "runtime-tokio-rustls", "chrono", "uuid"] }
tokio = { version = "1.22.0", features = ["macros", "rt", "rt-multi-thread"] }
uuid = { version = "1.2.1", features = ["v4"] }
